server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/routesdb
    username: routes
    password: routes
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
